#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — Unsqueeze: ASUS Vivobook power-clamp + fan fix installer.
# Works both from a clone (sudo bash other/unsqueeze/install.sh) and as a
# one-liner (curl ... | sudo bash) — it fetches its component files from the
# repo when they aren't next to it. Interactive; re-runnable.
# Non-interactive (defaults): UNSQUEEZE_ASSUME=1 bash other/unsqueeze/install.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=/etc/unsqueeze.conf

# tty_read — read a line from the terminal even when the script is piped
# (curl | sudo bash), so menus still work. Falls back to stdin for
# non-interactive use.
tty_read() {
  if [ -r /dev/tty ]; then
    read -r "$@" < /dev/tty
  else
    read -r "$@" 2>/dev/null || true
  fi
}

# tty-safe pause (shadow library version)
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  tty_read _ || true
}

# Override the generic wizard banner (no browser/API-key steps in this wizard).
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '  ASUS ships this laptop with the CPU power capped at 15W and a\n'
  printf '  fan curve that never spins up — so under load it crawls at\n'
  printf '  half speed while staying cold, like a lazy mode.\n\n'
  printf '  This fix raises the cap to 40W (25W on battery) and ramps the\n'
  printf '  fan to full when it gets hot. You pick the profile per stage\n'
  printf '  with the arrow keys. Choices are saved and applied at boot.\n\n'
  pause "Ready to start?"
}

MENU_SEL=1
# menu "prompt" "option1" "option2" ... — arrow-key selectable menu.
# Up/Down or j/k to move, Enter (or the number) to pick. First option is
# the recommended default. Falls back to option 1 when not interactive.
menu() {
  local prompt="$1"; shift
  local opts=("$@")
  local n=${#opts[@]}
  local sel=1 key seq rows=$((n + 2))
  local i c

  MENU_SEL=1
  [[ "${UNSQUEEZE_ASSUME:-0}" = "1" ]] && return
  [ -r /dev/tty ] || return

  while true; do
    printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
    i=1
    for c in "${opts[@]}"; do
      if [ "$i" -eq "$sel" ]; then
        printf '    %s▸ %s%s\n' "$GREEN" "$c" "$RESET"
      else
        printf '      %s\n' "$c"
      fi
      i=$((i+1))
    done
    printf '  %s↑/↓ or j/k move · Enter select%s\n' "$DIM" "$RESET"

    read -rsn1 key < /dev/tty
    case "$key" in
      $'\e')
        seq=""
        read -rsn2 -t 0.3 seq < /dev/tty || true
        case "$seq" in
          '[A') sel=$((sel > 1 ? sel - 1 : n)) ;;
          '[B') sel=$((sel < n ? sel + 1 : 1)) ;;
        esac
        ;;
      $'\n'|$'\r'|'') break ;;
      [1-9])
        [ "$key" -ge 1 ] && [ "$key" -le "$n" ] && sel=$key
        ;;
      j) sel=$((sel < n ? sel + 1 : 1)) ;;
      k) sel=$((sel > 1 ? sel - 1 : n)) ;;
    esac
    printf '\033[%dA\033[J' "$rows"
  done
  printf '\033[%dA\033[J' "$rows"
  MENU_SEL=$sel
}

if [[ "$(id -u)" -ne 0 ]]; then
  printf '%sRun with sudo:  sudo bash other/unsqueeze/install.sh%s\n' "$RED" "$RESET" >&2
  exit 1
fi

# ── Self-fetch: make the one-liner work. When the component files aren't
# next to this script (piped from curl), download them from the repo.
RAW_BASE="https://raw.githubusercontent.com/Apiratchai/dotfiles/main/other/unsqueeze"
DIR="$(dirname "${BASH_SOURCE[0]:-.}" 2>/dev/null || echo .)"
need_fetch=0
for f in unsqueeze-power.sh unsqueeze-fan.sh \
         unsqueeze-power.service unsqueeze-power.timer \
         unsqueeze-fan.service acpi_call.conf; do
  [ -f "$DIR/$f" ] || need_fetch=1
done
if [ "$need_fetch" = "1" ]; then
  if ! command -v curl >/dev/null 2>&1; then
    printf '%scurl is required for the one-liner install. Install it or clone the repo.%s\n' "$RED" "$RESET" >&2
    exit 1
  fi
  TDIR=$(mktemp -d)
  echo "  fetching component files from the repo..."
  for f in unsqueeze-power.sh unsqueeze-fan.sh \
           unsqueeze-power.service unsqueeze-power.timer \
           unsqueeze-fan.service acpi_call.conf; do
    curl -fsSL "$RAW_BASE/$f" -o "$TDIR/$f" || {
      printf '%sfailed to download %s%s\n' "$RED" "$f" "$RESET" >&2
      exit 1
    }
  done
  DIR="$TDIR"
fi

banner "Unsqueeze — ASUS Vivobook power/fan fix"

# ── Stage 1: detect the machine ───────────────────────────────────────────
stage "Detect laptop"
say "This fix targets ASUS Vivobooks/Zenbooks with an Alder Lake CPU"
say "whose EC firmware enforces a 15W power limit and a weak fan curve."
if [ -d /sys/class/powercap/intel-rapl-mmio:0 ]; then
  note "  ✓ MMIO RAPL zone present (the interface we must write)"
else
  warn "  ✗ intel-rapl-mmio:0 missing — this machine may not need the fix"
fi
if [ -d /sys/class/hwmon/hwmon4 ] && [ -r /sys/class/hwmon/hwmon4/fan1_input ]; then
  note "  ✓ ASUS fan control found"
else
  warn "  ✗ no ASUS fan hwmon found"
fi
model=$(cat /sys/class/dmi/id/product_name 2>/dev/null || echo unknown)
note "  machine: $model"
pause "Continue?"

# ── Stage 2: AC power budget ──────────────────────────────────────────────
stage "AC power budget"
menu "How much power on AC?" \
  "40W — best balance (recommended, measured peak)" \
  "45W — max throughput, lives at the 92C ceiling" \
  "35W — coolest and quietest"
case "$MENU_SEL" in
  1) PL1_AC=40000000; PL2_AC=65000000 ;;
  2) PL1_AC=45000000; PL2_AC=65000000 ;;
  3) PL1_AC=35000000; PL2_AC=45000000 ;;
esac
note "  → PL1 $((PL1_AC/1000000))W / PL2 $((PL2_AC/1000000))W on AC"

# ── Stage 3: fan behavior ─────────────────────────────────────────────────
stage "Fan behavior"
menu "When should the fan go full speed?" \
  "Balanced — full above 78C, quiet below 68C (recommended)" \
  "Aggressive — full above 72C, quiet below 62C" \
  "Auto only — leave the EC in charge (best with 35W)"
case "$MENU_SEL" in
  1) FAN_ON=78;  FAN_OFF=68; FAN_ENABLED=1 ;;
  2) FAN_ON=72;  FAN_OFF=62; FAN_ENABLED=1 ;;
  3) FAN_ON=95;  FAN_OFF=90; FAN_ENABLED=0 ;;
esac
note "  → full ≥${FAN_ON}C, back to auto ≤${FAN_OFF}C (enabled=${FAN_ENABLED})"

# ── Stage 4: battery budget ───────────────────────────────────────────────
stage "Battery power budget"
menu "How much power on battery?" \
  "25W — good performance on the go (recommended)" \
  "28W — AIPT-style ceiling, slightly less battery" \
  "15W — stock behavior, maximum battery life"
case "$MENU_SEL" in
  1) PL1_BAT=25000000; PL2_BAT=45000000 ;;
  2) PL1_BAT=28000000; PL2_BAT=45000000 ;;
  3) PL1_BAT=15000000; PL2_BAT=25000000 ;;
esac
note "  → PL1 $((PL1_BAT/1000000))W on battery"

# ── Stage 5: save config, install files, enable ───────────────────────────
stage "Install"
note "saving choices to $ENV_FILE"
touch "$ENV_FILE"
write_env PL1_AC      "${PL1_AC:-40000000}"
write_env PL2_AC      "${PL2_AC:-65000000}"
write_env PL1_BAT     "${PL1_BAT:-25000000}"
write_env PL2_BAT     "${PL2_BAT:-45000000}"
write_env FAN_ON      "${FAN_ON:-78}"
write_env FAN_OFF     "${FAN_OFF:-68}"
write_env FAN_ENABLED "${FAN_ENABLED:-1}"

# DIR was resolved (and files fetched if needed) before the banner.
install -m 0755 "$DIR/unsqueeze-power.sh" /usr/local/sbin/unsqueeze-power.sh
install -m 0755 "$DIR/unsqueeze-fan.sh"   /usr/local/sbin/unsqueeze-fan.sh
install -m 0644 "$DIR/unsqueeze-power.service" /etc/systemd/system/
install -m 0644 "$DIR/unsqueeze-power.timer"   /etc/systemd/system/
install -m 0644 "$DIR/unsqueeze-fan.service"   /etc/systemd/system/
install -m 0644 "$DIR/acpi_call.conf" /etc/modules-load.d/acpi_call.conf
note "  ✓ scripts and units installed"

if [ -e /proc/acpi/call ]; then
  note "  ✓ acpi_call already available"
else
  modprobe acpi_call 2>/dev/null || true
  if [ -e /proc/acpi/call ]; then
    note "  ✓ acpi_call loaded"
  else
    warn "  building acpi_call from source (nix-community/acpi_call)..."
    dnf install -y kernel-devel dkms make git 2>/dev/null || true
    if [ ! -d /tmp/acpi_call ]; then
      git clone --depth 1 https://github.com/nix-community/acpi_call.git /tmp/acpi_call 2>/dev/null || true
    fi
    ( cd /tmp/acpi_call && make dkms-add dkms-build dkms-install ) 2>/dev/null || true
    modprobe acpi_call 2>/dev/null || true
    if [ -e /proc/acpi/call ]; then
      note "  ✓ acpi_call built and loaded"
    else
      warn "  acpi_call unavailable (kernel update pending?) — fan will use the WMI fallback"
    fi
  fi
fi

systemctl daemon-reload
systemctl enable --now unsqueeze-power.service 2>/dev/null || true
systemctl enable --now unsqueeze-power.timer   2>/dev/null || true
# "Auto only" (FAN_ENABLED=0) keeps the fan service off entirely: the
# daemon exits immediately on a disabled config, and Restart=always
# would otherwise bounce it every 5s forever.
if [ "$FAN_ENABLED" = "1" ]; then
  systemctl enable --now unsqueeze-fan.service 2>/dev/null || true
  # Restart applies a changed /etc/unsqueeze.conf on re-runs
  # (enable --now is a no-op on an already-running unit).
  systemctl restart unsqueeze-fan.service 2>/dev/null || true
else
  systemctl disable --now unsqueeze-fan.service 2>/dev/null || true
fi
note "  ✓ services enabled"

# ── Stage 6: cleanup (only if present) ────────────────────────────────────
stage "Cleanup"
cleaned=0
if [ -f /tmp/acpi_ec/uninstall.sh ]; then
  bash /tmp/acpi_ec/uninstall.sh >/dev/null 2>&1 || true
  rm -rf /tmp/acpi_ec
  cleaned=1
fi
if dkms status 2>/dev/null | grep -q "acpi_ec"; then
  dkms remove acpi_ec/1.0.4 --all >/dev/null 2>&1 || true
  cleaned=1
fi
if [ -d /usr/src/acpi_ec-1.0.4 ]; then
  rm -rf /usr/src/acpi_ec-1.0.4
  cleaned=1
fi
if rpm -q nbfc-linux >/dev/null 2>&1; then
  dnf remove -y nbfc-linux >/dev/null 2>&1 || true
  cleaned=1
fi
if [ "$cleaned" = "1" ]; then
  note "  ✓ removed unused module/package leftovers"
else
  note "  nothing to clean up (fresh system — fine)"
fi

# ── Stage 7: verify ───────────────────────────────────────────────────────
stage "Verify"
ok=1
pl1=$(cat /sys/class/powercap/intel-rapl-mmio:0/constraint_0_power_limit_uw 2>/dev/null || echo 0)
if [ "$pl1" = "$PL1_AC" ]; then
  note "  ✓ MMIO PL1 = $((pl1/1000000))W (target ${PL1_AC})"
else
  warn "  ✗ MMIO PL1 = $pl1, expected $PL1_AC"
  ok=0
fi
fan_ok=1
if [ "$FAN_ENABLED" = "1" ]; then
  systemctl is-enabled unsqueeze-fan.service >/dev/null 2>&1 || fan_ok=0
fi
if systemctl is-enabled unsqueeze-power.service >/dev/null 2>&1 && \
   [ "$fan_ok" = "1" ]; then
  note "  ✓ services enabled"
else
  warn "  ✗ a service failed to enable"
  ok=0
fi
[ -e /proc/acpi/call ] && note "  ✓ acpi_call live" || warn "  ✗ acpi_call missing (fan uses fallback)"
printf '  %sQuick throughput check (16 threads, ~15s):%s\n' "$DIM" "$RESET"
openssl speed -multi 16 sha256 2>/dev/null | grep -E "^\s*sha256" | awk '{printf "     16-thread: %.1f GB/s (healthy ≈ 19+)\n", $NF/1024/1024}'
if [ "$ok" = "1" ]; then
  note "  all checks passed."
else
  warn "  see warnings above."
fi
pause "Press Enter for summary"

finish
note "Re-run this wizard any time to change the profile:"
note "  sudo bash other/unsqueeze/install.sh"
